// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCj5P_L5EknATPEN-DTMT-BNbHyYtYbpP4',
    appId: '1:15639496941:web:ed1d4de744951995ec24e4',
    messagingSenderId: '15639496941',
    projectId: 'pythonapp-dd681',
    authDomain: 'pythonapp-dd681.firebaseapp.com',
    databaseURL: 'https://pythonapp-dd681-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pythonapp-dd681.appspot.com',
    measurementId: 'G-KXDYVJLK2R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFA6oNLj3Kg_SDNp1elisJIDt2VXwTsyw',
    appId: '1:15639496941:android:8b533670b0cf2509ec24e4',
    messagingSenderId: '15639496941',
    projectId: 'pythonapp-dd681',
    databaseURL: 'https://pythonapp-dd681-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pythonapp-dd681.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCovWHb4uJcE4QI8e1joe0pmUNIeXTOev0',
    appId: '1:15639496941:ios:2842151d094bfcbfec24e4',
    messagingSenderId: '15639496941',
    projectId: 'pythonapp-dd681',
    databaseURL: 'https://pythonapp-dd681-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pythonapp-dd681.appspot.com',
    androidClientId: '15639496941-n0fl9rir2bafmd1qei9anlvq9dmv7pia.apps.googleusercontent.com',
    iosClientId: '15639496941-qh43ghpjgjsd78gs2f5bloq0nn64q51l.apps.googleusercontent.com',
    iosBundleId: 'com.pichet.pythonapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCovWHb4uJcE4QI8e1joe0pmUNIeXTOev0',
    appId: '1:15639496941:ios:2842151d094bfcbfec24e4',
    messagingSenderId: '15639496941',
    projectId: 'pythonapp-dd681',
    databaseURL: 'https://pythonapp-dd681-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pythonapp-dd681.appspot.com',
    androidClientId: '15639496941-n0fl9rir2bafmd1qei9anlvq9dmv7pia.apps.googleusercontent.com',
    iosClientId: '15639496941-qh43ghpjgjsd78gs2f5bloq0nn64q51l.apps.googleusercontent.com',
    iosBundleId: 'com.pichet.pythonapp',
  );
}
